numero1 = float(input('Digite primer numero: '))
numero2 = float(input('Digite segundo numero: '))
print('Suma: ', numero1 + numero2)
print('Resta: ', numero1 - numero2)
print('Multiplicacion: ', numero1 * numero2)
print('Division: ', numero1 / numero2)
print('Potencia: ', numero1 ** numero2)